/*
 * Copyright (c) 2021, Alibaba Group;
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *    http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.havenask.engine.rpc;

import org.havenask.test.HavenaskTestCase;

public class TargetInfoTests extends HavenaskTestCase {
    public void testParseSearcher() {
        String targetStr = "{\n"
            + "\t\"app_info\":{\n"
            + "\t\t\"config_path\":\"\",\n"
            + "\t\t\"keep_count\":20\n"
            + "\t},\n"
            + "\t\"biz_info\":{\n"
            + "\t\t\"default\":{\n"
            + "\t\t\t\"config_path\":\"/usr/share/havenask/data_havenask/config/bizs/0\",\n"
            + "\t\t\t\"custom_biz_info\":{},\n"
            + "\t\t\t\"keep_count\":5\n"
            + "\t\t}\n"
            + "\t},\n"
            + "\t\"custom_app_info\":{},\n"
            + "\t\"service_info\":{\n"
            + "\t\t\"cm2\":{\n"
            + "\t\t\t\"topo_info\":\"general.default:1:0:1371640948:100:2400309353:-1:true|general.default_agg:1:0:"
            + "1371640948:100:2400309353:-1:true|general.default_sql:1:0:1371640948:100:2400309353:-1:true|"
            + "general.para_search_2:1:0:1371640948:100:2400309353:-1:true|general.para_search_4:1:0:1371640948:100:"
            + "2400309353:-1:true|\"\n"
            + "\t\t},\n"
            + "\t\t\"part_count\":0,\n"
            + "\t\t\"part_id\":0,\n"
            + "\t\t\"version\":0\n"
            + "\t},\n"
            + "\t\"table_info\":{\n"
            + "\t\t\"test3\":{\n"
            + "\t\t\t\"0\":{\n"
            + "\t\t\t\t\"config_path\":\"/usr/share/havenask/data_havenask/config/table/0\",\n"
            + "\t\t\t\t\"force_online\":false,\n"
            + "\t\t\t\t\"group_name\":\"default_group_name\",\n"
            + "\t\t\t\t\"index_root\":\"/usr/share/havenask/data_havenask/local_search_12000/general_0/runtimedata\",\n"
            + "\t\t\t\t\"partitions\":{\n"
            + "\t\t\t\t\t\"0_65535\":{\n"
            + "\t\t\t\t\t\t\"check_index_path\":\"\",\n"
            + "\t\t\t\t\t\t\"deploy_status\":2,\n"
            + "\t\t\t\t\t\t\"deploy_status_map\":[\n"
            + "\t\t\t\t\t\t\t[\n"
            + "\t\t\t\t\t\t\t\t0,\n"
            + "\t\t\t\t\t\t\t\t{\n"
            + "\t\t\t\t\t\t\t\t\t\"local_config_path\":\"/usr/share/havenask/data_havenask/local_search_12000/general_0/"
            + "zone_config/table/test3/0/\",\n"
            + "\t\t\t\t\t\t\t\t\t\"deploy_status\":2\n"
            + "\t\t\t\t\t\t\t\t}\n"
            + "\t\t\t\t\t\t\t]\n"
            + "\t\t\t\t\t\t],\n"
            + "\t\t\t\t\t\t\"inc_version\":-1,\n"
            + "\t\t\t\t\t\t\"keep_count\":1,\n"
            + "\t\t\t\t\t\t\"loaded_config_path\":\"\",\n"
            + "\t\t\t\t\t\t\"loaded_index_root\":\"\",\n"
            + "\t\t\t\t\t\t\"local_index_path\":\"/usr/share/havenask/data_havenask/local_search_12000/general_0/"
            + "runtimedata/test3/generation_0/partition_0_65535\",\n"
            + "\t\t\t\t\t\t\"rt_status\":0,\n"
            + "\t\t\t\t\t\t\"schema_version\":0,\n"
            + "\t\t\t\t\t\t\"table_load_type\":0,\n"
            + "\t\t\t\t\t\t\"table_status\":3,\n"
            + "\t\t\t\t\t\t\"table_type\":0\n"
            + "\t\t\t\t\t}\n"
            + "\t\t\t\t},\n"
            + "\t\t\t\t\"raw_index_root\":\"\",\n"
            + "\t\t\t\t\"rt_status\":0,\n"
            + "\t\t\t\t\"table_mode\":0,\n"
            + "\t\t\t\t\"table_type\":0,\n"
            + "\t\t\t\t\"timestamp_to_skip\":-1,\n"
            + "\t\t\t\t\"total_partition_count\":0\n"
            + "\t\t\t}\n"
            + "\t\t},\n"
            + "\t\t\"test\":{\n"
            + "\t\t\t\"0\":{\n"
            + "\t\t\t\t\"config_path\":\"/usr/share/havenask/data_havenask/config/table/0\",\n"
            + "\t\t\t\t\"force_online\":false,\n"
            + "\t\t\t\t\"group_name\":\"default_group_name\",\n"
            + "\t\t\t\t\"index_root\":\"/usr/share/havenask/data_havenask/local_search_12000/general_0/runtimedata\",\n"
            + "\t\t\t\t\"partitions\":{\n"
            + "\t\t\t\t\t\"0_65535\":{\n"
            + "\t\t\t\t\t\t\"check_index_path\":\"\",\n"
            + "\t\t\t\t\t\t\"deploy_status\":2,\n"
            + "\t\t\t\t\t\t\"deploy_status_map\":[\n"
            + "\t\t\t\t\t\t\t[\n"
            + "\t\t\t\t\t\t\t\t0,\n"
            + "\t\t\t\t\t\t\t\t{\n"
            + "\t\t\t\t\t\t\t\t\t\"local_config_path\":\"/usr/share/havenask/data_havenask/local_search_12000/general_0/"
            + "zone_config/table/test/0/\",\n"
            + "\t\t\t\t\t\t\t\t\t\"deploy_status\":2\n"
            + "\t\t\t\t\t\t\t\t}\n"
            + "\t\t\t\t\t\t\t]\n"
            + "\t\t\t\t\t\t],\n"
            + "\t\t\t\t\t\t\"inc_version\":0,\n"
            + "\t\t\t\t\t\t\"keep_count\":1,\n"
            + "\t\t\t\t\t\t\"loaded_config_path\":\"/usr/share/havenask/data_havenask/config/table/0\",\n"
            + "\t\t\t\t\t\t\"loaded_index_root\":\"/usr/share/havenask/data_havenask/local_search_12000/general_0/runtimedata\",\n"
            + "\t\t\t\t\t\t\"local_index_path\":\"/usr/share/havenask/data_havenask/local_search_12000/general_0/"
            + "runtimedata/test/generation_0/partition_0_65535\",\n"
            + "\t\t\t\t\t\t\"rt_status\":0,\n"
            + "\t\t\t\t\t\t\"schema_version\":0,\n"
            + "\t\t\t\t\t\t\"table_load_type\":0,\n"
            + "\t\t\t\t\t\t\"table_status\":6,\n"
            + "\t\t\t\t\t\t\"table_type\":0\n"
            + "\t\t\t\t\t}\n"
            + "\t\t\t\t},\n"
            + "\t\t\t\t\"raw_index_root\":\"\",\n"
            + "\t\t\t\t\"rt_status\":0,\n"
            + "\t\t\t\t\"table_mode\":0,\n"
            + "\t\t\t\t\"table_type\":0,\n"
            + "\t\t\t\t\"timestamp_to_skip\":-1,\n"
            + "\t\t\t\t\"total_partition_count\":0\n"
            + "\t\t\t}\n"
            + "\t\t},\n"
            + "\t\t\"test9\":{\n"
            + "\t\t\t\"0\":{\n"
            + "\t\t\t\t\"config_path\":\"/usr/share/havenask/data_havenask/config/table/0\",\n"
            + "\t\t\t\t\"force_online\":false,\n"
            + "\t\t\t\t\"group_name\":\"default_group_name\",\n"
            + "\t\t\t\t\"index_root\":\"/usr/share/havenask/data_havenask/local_search_12000/general_0/runtimedata\",\n"
            + "\t\t\t\t\"partitions\":{\n"
            + "\t\t\t\t\t\"0_65535\":{\n"
            + "\t\t\t\t\t\t\"check_index_path\":\"\",\n"
            + "\t\t\t\t\t\t\"deploy_status\":2,\n"
            + "\t\t\t\t\t\t\"deploy_status_map\":[\n"
            + "\t\t\t\t\t\t\t[\n"
            + "\t\t\t\t\t\t\t\t0,\n"
            + "\t\t\t\t\t\t\t\t{\n"
            + "\t\t\t\t\t\t\t\t\t\"local_config_path\":\"/usr/share/havenask/data_havenask/local_search_12000/general_0/"
            + "zone_config/table/test9/0/\",\n"
            + "\t\t\t\t\t\t\t\t\t\"deploy_status\":2\n"
            + "\t\t\t\t\t\t\t\t}\n"
            + "\t\t\t\t\t\t\t]\n"
            + "\t\t\t\t\t\t],\n"
            + "\t\t\t\t\t\t\"inc_version\":0,\n"
            + "\t\t\t\t\t\t\"keep_count\":1,\n"
            + "\t\t\t\t\t\t\"loaded_config_path\":\"/usr/share/havenask/data_havenask/config/table/0\",\n"
            + "\t\t\t\t\t\t\"loaded_index_root\":\"/usr/share/havenask/data_havenask/local_search_12000/general_0/runtimedata\",\n"
            + "\t\t\t\t\t\t\"local_index_path\":\"/usr/share/havenask/data_havenask/local_search_12000/general_0/"
            + "runtimedata/test9/generation_0/partition_0_65535\",\n"
            + "\t\t\t\t\t\t\"rt_status\":0,\n"
            + "\t\t\t\t\t\t\"schema_version\":0,\n"
            + "\t\t\t\t\t\t\"table_load_type\":0,\n"
            + "\t\t\t\t\t\t\"table_status\":6,\n"
            + "\t\t\t\t\t\t\"table_type\":0\n"
            + "\t\t\t\t\t}\n"
            + "\t\t\t\t},\n"
            + "\t\t\t\t\"raw_index_root\":\"\",\n"
            + "\t\t\t\t\"rt_status\":0,\n"
            + "\t\t\t\t\"table_mode\":0,\n"
            + "\t\t\t\t\"table_type\":0,\n"
            + "\t\t\t\t\"timestamp_to_skip\":-1,\n"
            + "\t\t\t\t\"total_partition_count\":0\n"
            + "\t\t\t}\n"
            + "\t\t},\n"
            + "\t\t\"in0\":{\n"
            + "\t\t\t\"0\":{\n"
            + "\t\t\t\t\"config_path\":\"/usr/share/havenask/data_havenask/config/table/0\",\n"
            + "\t\t\t\t\"force_online\":false,\n"
            + "\t\t\t\t\"group_name\":\"default_group_name\",\n"
            + "\t\t\t\t\"index_root\":\"/usr/share/havenask/data_havenask/local_search_12000/general_0/runtimedata\",\n"
            + "\t\t\t\t\"partitions\":{\n"
            + "\t\t\t\t\t\"0_65535\":{\n"
            + "\t\t\t\t\t\t\"check_index_path\":\"\",\n"
            + "\t\t\t\t\t\t\"deploy_status\":2,\n"
            + "\t\t\t\t\t\t\"deploy_status_map\":[\n"
            + "\t\t\t\t\t\t\t[\n"
            + "\t\t\t\t\t\t\t\t1,\n"
            + "\t\t\t\t\t\t\t\t{\n"
            + "\t\t\t\t\t\t\t\t\t\"local_config_path\":\"/usr/share/havenask/data_havenask/local_search_12000/general_0/"
            + "zone_config/table/in0/0/\",\n"
            + "\t\t\t\t\t\t\t\t\t\"deploy_status\":2\n"
            + "\t\t\t\t\t\t\t\t}\n"
            + "\t\t\t\t\t\t\t]\n"
            + "\t\t\t\t\t\t],\n"
            + "\t\t\t\t\t\t\"inc_version\":1,\n"
            + "\t\t\t\t\t\t\"keep_count\":1,\n"
            + "\t\t\t\t\t\t\"loaded_config_path\":\"/usr/share/havenask/data_havenask/config/table/0\",\n"
            + "\t\t\t\t\t\t\"loaded_index_root\":\"/usr/share/havenask/data_havenask/local_search_12000/general_0/runtimedata\",\n"
            + "\t\t\t\t\t\t\"local_index_path\":\"/usr/share/havenask/data_havenask/local_search_12000/general_0/"
            + "runtimedata/in0/generation_0/partition_0_65535\",\n"
            + "\t\t\t\t\t\t\"rt_status\":0,\n"
            + "\t\t\t\t\t\t\"schema_version\":0,\n"
            + "\t\t\t\t\t\t\"table_load_type\":0,\n"
            + "\t\t\t\t\t\t\"table_status\":6,\n"
            + "\t\t\t\t\t\t\"table_type\":0\n"
            + "\t\t\t\t\t}\n"
            + "\t\t\t\t},\n"
            + "\t\t\t\t\"raw_index_root\":\"\",\n"
            + "\t\t\t\t\"rt_status\":0,\n"
            + "\t\t\t\t\"table_mode\":0,\n"
            + "\t\t\t\t\"table_type\":0,\n"
            + "\t\t\t\t\"timestamp_to_skip\":-1,\n"
            + "\t\t\t\t\"total_partition_count\":0\n"
            + "\t\t\t}\n"
            + "\t\t}\n"
            + "\t},\n"
            + "\t\"target_version\":0\n"
            + "}";

        TargetInfo targetInfo = TargetInfo.parse(targetStr);
        String targetToStr = targetInfo.toString();
        assertEquals(targetStr, targetToStr);
    }

    public void testParseQrs() {
        String targetStr = "{\n"
            + "\t\"app_info\":{\n"
            + "\t\t\"config_path\":\"\",\n"
            + "\t\t\"keep_count\":20\n"
            + "\t},\n"
            + "\t\"biz_info\":{\n"
            + "\t\t\"default\":{\n"
            + "\t\t\t\"config_path\":\"/usr/share/havenask/data_havenask/config/bizs/0\",\n"
            + "\t\t\t\"custom_biz_info\":{},\n"
            + "\t\t\t\"keep_count\":5\n"
            + "\t\t}\n"
            + "\t},\n"
            + "\t\"custom_app_info\":{},\n"
            + "\t\"service_info\":{\n"
            + "\t\t\"cm2\":{\n"
            + "\t\t\t\"topo_info\":\"ha3.general.default:1:0:1457961441:100:2400309353:-1:true|ha3.general.para_search_2:"
            + "1:0:1457961441:100:2400309353:-1:true|ha3.general.para_search_4:1:0:1457961441:100:2400309353:-1:true|\"\n"
            + "\t\t},\n"
            + "\t\t\"part_count\":0,\n"
            + "\t\t\"part_id\":0,\n"
            + "\t\t\"version\":0\n"
            + "\t},\n"
            + "\t\"table_info\":{},\n"
            + "\t\"target_version\":0\n"
            + "}";

        TargetInfo targetInfo = TargetInfo.parse(targetStr);
        String targetToStr = targetInfo.toString();
        assertEquals(targetStr, targetToStr);
    }
}
