# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle check part 3

on:
  push:
    branches-ignore:
      - 'backport/**'
      - 'create-pull-request/**'
      - 'dependabot/**'
      - 'gh-readonly-queue/*'
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  gradle-check:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Havenask Federation repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK 15
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run Tests
        run: cd elastic-fed; ./gradlew checkPart1 -x integTest  -x test -x internalClusterTest -x asyncIntegTest -x javaRestTest -x yamlRestTest -x pooledInternalClusterTest -x pooledTest